// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpaS7uQMizJBJqr_QGuSlZfNyFspA4Sow',
    appId: '1:457529885849:web:ae19d7e75df7844f97a408',
    messagingSenderId: '457529885849',
    projectId: 'tech-talk-hub',
    authDomain: 'tech-talk-hub.firebaseapp.com',
    storageBucket: 'tech-talk-hub.firebasestorage.app',
    measurementId: 'G-4PJB85ENJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pcBU13fb17rrmtA8JLILw5Y0Sfo1tpA',
    appId: '1:457529885849:android:04300211109b2eb497a408',
    messagingSenderId: '457529885849',
    projectId: 'tech-talk-hub',
    storageBucket: 'tech-talk-hub.firebasestorage.app',
  );
}
